/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AttestRouteImport } from './routes/attest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BadgeIdRouteImport } from './routes/badge.$id'

const AttestRoute = AttestRouteImport.update({
  id: '/attest',
  path: '/attest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeIdRoute = BadgeIdRouteImport.update({
  id: '/badge/$id',
  path: '/badge/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attest': typeof AttestRoute
  '/badge/$id': typeof BadgeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attest': typeof AttestRoute
  '/badge/$id': typeof BadgeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attest': typeof AttestRoute
  '/badge/$id': typeof BadgeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attest' | '/badge/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attest' | '/badge/$id'
  id: '__root__' | '/' | '/attest' | '/badge/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttestRoute: typeof AttestRoute
  BadgeIdRoute: typeof BadgeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/attest': {
      id: '/attest'
      path: '/attest'
      fullPath: '/attest'
      preLoaderRoute: typeof AttestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge/$id': {
      id: '/badge/$id'
      path: '/badge/$id'
      fullPath: '/badge/$id'
      preLoaderRoute: typeof BadgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttestRoute: AttestRoute,
  BadgeIdRoute: BadgeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
